### ISSUE TITLE
no member named pickSources 

### ISSUE THREAD

**Issue by rohitvarkey** [DynoGraph/stinger-dynograph#2]
I'm trying to build stinger-dynograph on the latest commit and I get this error.

```make
/root/.julia/v0.5/StingerWrapper/deps/stinger-dynograph/dynograph.cpp: In member function 'void StingerAlgorithm::pickSources()':
stinger-dynograph/dynograph.cpp:290:16: error: 'class gt::stinger::BreadthFirstSearch' has no member named 'pickSource'
             b->pickSource(&data);
                ^
stinger-dynograph/dynograph.cpp:292:16: error: 'class gt::stinger::BetweennessCentrality' has no member named 'pickSources'
             b->pickSources(&data);
                ^
```

The `pickSources` functions seem to have been removed in https://github.com/DynoGraph/stinger/commit/c51322ae26e4ed8ebae59cf34dc1f10a6c5988af. But `dynograph.cpp` still tries to use those functions.

**Comment by ehein6** [comment]
Thanks for letting me know, this has been fixed. Will be implementing a Travis build soon to make this easier to catch.
